language: java
jdk:
- oraclejdk7
script: ./travis_build.sh
env:
  global:
  - BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
  - secure: R1llXwWLwJ7T8mCpBtwErq9Hqa23LmEjGEGvTjo6+q9UcAq7zBPFetqnN/Z9EiQoJyd2VBT8P5PdbOQN3U7EbirDXHyoM9OaM7NLhmLK3RsVDqSp19mh2QR+v13m6sfIkAO57r0gZlUbl0MLwGz+yBYpDSGvwcrhyf1Dg3mNTT4=
  - secure: CqWvT/jl531hQ4tZKTX976rG/lJzQnK2W6pgjAL3Ew0+73vxY/kAm8BaD4Wy4zSGDgdqdnutf/NNMviTeI4rz7C6EyKrvLDSlF+/cJoY8+ilyR/3dSZAyIhzQezqn+VgwQVcT/4J2F58nPkFAb0jjW1JjaIRJ5nrqb8+WSbb1pw=
  - secure: H3dcTwChj6/lgNcIw+BNzUdY5Gk+AmVMzSSbd5Q1PC30uySQl72DygZwm1SLZU0Vgj8D+rQu30RBBZPjxwiUvcIQ1YzEu0DTNFbuqKsIbevHJCrp5J9BOzgHmUjUwPW9nv3bQPn/wuOF5wbO3o6ot/4aGKP8X1B6m6eoDYyVGW0=

